import { hoyArgentina } from '../fechas'
import { useEffect, useState } from 'react'
import * as api from '../api'
import Aviso from '../componentes/Aviso'
import { plata, fecha } from '../formato'
export default function Financiacion({ obra }) {
  const [d, setD] = useState({ capital: '', tasa_anual: 0, meses: 12, inicio: hoyArgentina(), ajuste_mensual: 0, adelanto_meses: 0 })
  const [r, setR] = useState(null); const [error, setError] = useState(null); const set = (k) => (e) => setD({ ...d, [k]: e.target.value })
  useEffect(() => { api.get(`/api/obras/${obra.id}/financiacion`).then((x) => x && setD({ ...x, capital: String(x.capital), tasa_anual: String(x.tasa_anual), meses: String(x.meses), ajuste_mensual: String(x.ajuste_mensual), adelanto_meses: String(x.adelanto_meses) })).catch(() => {}) }, [obra.id])
  const calcular = async (e) => { e.preventDefault(); try { const datos = { ...d, capital: Number(d.capital), tasa_anual: Number(d.tasa_anual), meses: Number(d.meses), ajuste_mensual: Number(d.ajuste_mensual), adelanto_meses: Number(d.adelanto_meses) }; await api.put(`/api/obras/${obra.id}/financiacion`, datos); setR(await api.post(`/api/obras/${obra.id}/financiacion/proyeccion`, datos)) } catch (x) { setError(x) } }
  return <><Aviso error={error} alCerrar={() => setError(null)} /><div className="ob-toolbar"><span className="ob-label">Financiación</span><span className="ob-toolbar__meta">Proyección de cuotas y escenarios de adelanto</span></div><form className="ob-card" style={{ margin: 'var(--ob-gap-4)', padding: 'var(--ob-gap-4)', display: 'grid', gap: 'var(--ob-gap-3)', gridTemplateColumns: 'repeat(auto-fit,minmax(10rem,1fr))' }} onSubmit={calcular}><label><span className="ob-label">Capital</span><input className="ob-input" required value={d.capital} onChange={set('capital')} /></label><label><span className="ob-label">Tasa anual (%)</span><input className="ob-input" value={d.tasa_anual} onChange={set('tasa_anual')} /></label><label><span className="ob-label">Plazo (meses)</span><input className="ob-input" type="number" value={d.meses} onChange={set('meses')} /></label><label><span className="ob-label">Inicio</span><input className="ob-input" type="date" value={d.inicio} onChange={set('inicio')} /></label><label><span className="ob-label">Ajuste mensual (%)</span><input className="ob-input" value={d.ajuste_mensual} onChange={set('ajuste_mensual')} /></label><label><span className="ob-label">Adelantar desde cuota</span><input className="ob-input" type="number" value={d.adelanto_meses} onChange={set('adelanto_meses')} /></label><button className="ob-btn ob-btn--primario" type="submit">Calcular proyección</button></form>{r && <><div className="ob-toolbar"><span>Cuota inicial <b>{plata(r.cuota_inicial)}</b> · Total <b>{plata(r.total_proyectado)}</b> · Ahorro estimado por adelanto <b>{plata(r.ahorro_adelantando)}</b></span></div><div className="ob-tablewrap"><table className="ob-table"><thead><tr><th>N°</th><th>Fecha</th><th className="ob-num">Cuota</th><th className="ob-num">Interés</th><th className="ob-num">Amortización</th><th className="ob-num">Saldo</th></tr></thead><tbody>{r.cuotas.map((x) => <tr key={x.numero}><td>{x.numero}</td><td>{fecha(x.fecha)}</td><td className="ob-num">{plata(x.pago)}</td><td className="ob-num">{plata(x.interes)}</td><td className="ob-num">{plata(x.amortizacion)}</td><td className="ob-num">{plata(x.saldo)}</td></tr>)}</tbody></table></div></>}</>
}
